version: '3.8'

services:
  # API Gateway - Main entry point
  gateway:
    build:
      context: ./packages/gateway-api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - GATEWAY_PORT=3000
      - COMMENTS_SERVICE_URL=http://comments:3001

            depends_on:
        - comments
    networks:
      - part-internship-network
    restart: unless-stopped

  # Comments Service
  comments:
    build:
      context: ./apps/recruitment/comments
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=file:./data/comments.db
    volumes:
      - comments-data:/app/data
    networks:
      - part-internship-network
    restart: unless-stopped





  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - gateway
    networks:
      - part-internship-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  comments-data:
    driver: local

networks:
  part-internship-network:
    driver: bridge
